### PR TITLE
Feature commit of task 3 lesson 1 and 2

### PR DESCRIPTION
**Pull request by Echemartins**
@ChidiPatrick
@Promise-J
Kindly review my lesson 1 and 2 task 3

### CODE REVIEW

**Review by promise-J — APPROVED** [review]
Great work. You can go ahead and merge.

However, you could also go ahead to merge to main

**Review by promise-J — APPROVED** [review]
Great work. You can go ahead and merge.

However, you could also go ahead to merge to main

**Comment by Echemartins** [comment]
Thank you

**Review by promise-J — APPROVED** [review]
Great work. Please go ahead and merge

**Pull request merged**
